amazon_scrapping/scrapping.py

#14  fixed the issue with relevant comments as well 
-thankyou 
kairveeehh

fixed the issue in scrapping.py 

---

Movie_review_imdb_scrapping.ipynb
amazon_scrapping/scrapping.py

#15 documented it properly and fixed the typos

#15 issue fixed 

---

.github/ISSUE_TEMPLATE/bug_report.md

Template to report_bug.md

---

News_data_scrapping/README.md
News_data_scrapping/code.py

Developed of a Python-based news data analysis tool. This project aims to analyze news data from various sources and provide insights into trends, sentiments, and key topics.
Issue: #33 
**Screenshots::**

Added Python News Data Scrapping (Issue: #33)

---

.ipynb_checkpoints/clustering movie review-checkpoint.ipynb

Integrating sentiment analysis will enable us to classify each review as positive, negative, or neutral, providing valuable insights into the general sentiment surrounding particular movies.
Solved the issue #17

Addition of sentiment analysis function

---

.github/workflows/autocomment-pr-merge.yml

Fixes #86 
@sanjay-kv please review this PR and merge it if it is good to go

added auto commenting feat for PR merged

---

Web_app/README.md
Web_app/instructions.txt

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
[Please include a brief description of the changes or features added]

Added README File for Web_app Folder 

---

backlog/ClusteringOfIMDBMovies.py

https://github.com/Recode-Hive/Scrape-ML/pull/108
Two people i.e- I Mercia Jeno and Bhakti  Kalyankasture have collaborated to the issue https://github.com/Recode-Hive/Scrape-ML/issues/64, that has been merged already.

Collaborate

---

Web_app/requirements.txt

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
[Please include a brief description of the changes or features added]

added dependency file

---

.github/workflows/close-old-issue.yml

Fixes #100 
This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

created close-old-issue.yml

---

.github/workflows/autocomment-iss-close.yml

Fixes #99 
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

created autocomment-iss-close.yml

---

.github/workflows/close-old-pr.yml

Fixes #101 
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

created close-old-pr.yml

---

.ipynb_checkpoints/clustering movie review-checkpoint.ipynb

There are few changing that i've tried to keep correct them as well and if you found something wrong then let you ping me here...
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
[Please include a brief description of the changes or features added]

Update clustering movie review-checkpoint.ipynb

---

abstract_training.ipynb

Issue number #118 
I have added a model as stated in the issue
A model to categorize medical abstracts as objectives, background, methods, results and conclusions

A model to categorize medical abstracts as objectives, background, methods, results and conclusions

---

README.md

I have replaced the picture with the updated one.
@sanjay-kv "Try to merge the code without review."

Update README.md [Redesign README Image]

---

Web_app/streamlit_app.py

Fixes issue #125 
I have modified streamlit_app.py to check for 'user_review'

Fixed 'user_review' issue in streamlit app

---

backlog/Movie-genre-prediction/Movie-Genre-Prediction.ipynb

[#92] Resolved.
This is a movie genre prediction model. In this PR, I have tested Tf-idf and Bag of Words with Logistic Regression. Bag of Words with Logictic Regression was found to be most useful after dimensionality reduction so final Testing has been done using it.
The genre prediction model takes the plot of a movie, and then predicts to which  genre it belongs.
- [ X] Feature enhancement
N/A
- [x ] I have performed a self-review of my code
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
N/A

Movie Genre prediction complete. Resolves [#92]

---

README.md

Comprehensibility issue in cloning repository section
Added clear and separate instructions for cloning repository using SSH and HTTPS. Also added a step to navigate to the project directory on the local system.
NA
None

Edited installation in README to make it clearer

---

CODE_OF_CONDUCT.md

Fixed Issue #152 by adding a code of conduct markdown file into the github repository for upcoming GSSOC'24 contributors.

Fixing Issue #54

---

Web_app/Updated_Scrapper.py

#161 
-Custom Exception: Introducing a ScrapingError exception class allows you to handle errors specifically related to the scraping process.
-Explicit Timeouts: Using LOAD_MORE_TIMEOUT and SCRAPE_TIMEOUT makes the code more readable and easier to adjust the wait times for different operations.
-Error Handling in main: The main function now handles the ScrapingError exception, allowing the script to gracefully skip pages that encounter scraping issues.
-Constant Use: Using constants like MAX_PAGES improves readability and maintainability.
- [✅ ] Documentation update
- [ ✅] I have performed a self-review of my code
- [✅ ] I have read and followed the Contribution Guidelines.
- [ ✅] I have tested the changes thoroughly …

Adding Updated_Scrapper.py

---

Movie_review_rotten_tomatoes.ipynb
data_scrapped/data_rotten_tomatoes.csv

This is a PR for another file of code , in which we can get the reviews of the rottentomatoes.com website.
The code is same as getting the reviews from IMDB , but have done necessary changes and have commented everything.
And a csv file where we have scrapped the data. 
Please have a check on it , I have already opened the issue , as I am contributing as a GSSOC contributor.

Add another dataset other than IMDB

---

amazon_scrapping/Gui_ocr.py

please check gui inrterface in this i will b taking three inputs 
>website url
>name of extracted text file
>loacation in desktop browse and store
will be adding new features further to enhance extraction acccuracy 
demo working video- https://drive.google.com/file/d/1hVdfS-fVClkD2vxlcQh5mUy9X1s5LgZ9/view?usp=sharing

Gui interface added

---

.github/ISSUE_TEMPLATE/documentation.md

Added issues template for documentation issues 

---

Web_app/Scarper.py

#171 
This PR addresses the issue related to the executable_path parameter used in the Selenium WebDriver initialization. The error encountered was due to the deprecated use of executable_path when setting up the Chrome WebDriver, leading to a traceback error during script execution. The fix involves updating the Selenium WebDriver initialization to use the recommended Service class from selenium.webdriver.chrome.service along with webdriver_manager for automatic driver management.

[Error Solved] 'executable_path' 

---

Web_app/Scarper.py

Reverts Recode-Hive/Scrape-ML#172

Revert "[Error Solved] 'executable_path' "

---

Smart_select features/smart_select_gui.py

Gui interface created  it will extract any kind of text from screenshots in GUI interface
user can directly navigate and add screenshot from desktop and text will be extracted from ss and shown in interface ,if user wants to store they can also create file and store from interface
output 
i will further refine in accuracy feature

Smart select feature gui created 

---

.github/workflows/issues-tags.yml

fixes #194 
This PR introduces an automatic labeling system to our project management platform. The system enhances issue management efficiency by automating the process of labeling issues based on predefined criteria. Manual labeling is time-consuming and prone to inconsistencies. Automating this process ensures consistent categorization across the project.
- This PR includes changes to introduce automatic labeling.
- The labels "gssoc" and "good new issue" will be automatically added to newly opened issues.

Added tags workflow flow for issues

---

Web_app/pages/2_Movie_Recommendation.py

Updated movies.csv and similarity.pkl paths
Issue #248 - File not found: ./pages/similarity.pkl File not found: ./movies.csv
Fixed the paths of movies.csv and similarity.pkl in 2_Movie_Recommendation.py

Updated 2_Movie_Recommendation.py

---

README.md

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
This pull request introduces a troubleshooting section to the documentation, addressing common installation and usage issues. Minor grammatical corrections were also made to improve clarity throughout the documentation.
not applicable since my work was focused on documentation.
This update aims to enhance the user experience by providing clear guidance on troubleshooting common issues that users may face while using the scraper.

Troubleshooting Section & Clarity Improvements

---

README.md

none
FIXES #281 
CLOSE #281 
🚀 Pull Request
Description
ADDED HACKTOBERFEST AND GSSOC BANNER ON THE README
- [ x] Feature enhancement
- [x ] Documentation update
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
PLEASE ADD LEVEL 2 OR LEVEL 3 AS GSSOC IS GOING TO BE OVER IN 2 DAYS

Update README.md ADDED HACKTOBERFEST AND GSSOC BANNER ON THE README

---

Web_app/Home_Page.py

Color changes to black for movie maestro. Please do assign under gssoc'24 extd and hacktoberfest
ISSUE NO: #288 
I have changes the css for visibility from yellow to black.

Changed the color to black

---

README.md

Solved the issue - #292 
Updated README.md command to run the application
- [ X ] Documentation update
- [ x ] I have performed a self-review of my code
- [ x ] I have read and followed the Contribution Guidelines.
- [ x ] I have tested the changes thoroughly before submitting this pull request.
- [ x  ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x ] I have commented my code, particularly in hard-to-understand areas.

#292 : Updated README.md to run the application

---

.github/ISSUE_TEMPLATE/custom.yml
README.md

Creating a custom issue template for the project can significantly enhance the process of issue reporting and tracking. Here’s why it is necessary and some key components to include in your custom issue template:
- **Consistency**: A custom template ensures that all issues follow a consistent format, making it easier for contributors and maintainers to understand and categorize them.
- **Clarity**: It helps guide users to provide all necessary information, reducing back-and-forth communication for missing details.
- **Efficiency**: Streamlining the issue creation process helps contributors focus on the problem rather than figuring out what information is needed.
1. **Title**: A brief summary of the issue.
2. **Description**: A detailed explanation of the issue, including steps to …

CREATE CUSTOM ISSUE TEMPLATE 

---

README.md

ADD stargazers and Forker's sections to the README file.
The addition of the stargazers and forkers sections enhances the visibility of contributions to the project and encourages community engagement. This feature showcases appreciation for users who have interacted with the repository.

ADD stargazers and Forkers

---

Web_app/pages/MoviePol.py

#291 
Changed the path of pollmovie.csv in Web_app/pages/MoviePol.py to make it suitable for streamlit deployment
- [ x] Bug fix
- [ X ] I have performed a self-review of my code
- [ X ] I have read and followed the Contribution Guidelines.
- [ X ] I have tested the changes thoroughly before submitting this pull request.
- [ X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X ] I have commented my code, particularly in hard-to-understand areas.

fix: #291 path of 'pollmovies.csv' changed

---

Web_app/pages/GitContributors.py

#307 
Solved the bug of contributors page not loading properly

Solved contributors page bug
