Movie_review_imdb_scrapping.ipynb

Have made changes to the Movie_review_imdb_scrapping.ipynb to display the movie tags and movie review emails as desired

#Filtering movie tags and movie review mails

---

README.md
amazon_scrapping/README.md

Hello PA,
->Changed the git clone repo link.
->Added 3 step to clone a repo
->Removed small errors 
->Added a link to the main Github repo for contributors to view.

README Updated

---

Movie_review_imdb_scrapping.ipynb

Solved the issue stated at #13

Added Sentimental Analysis Code #13

---

Scrapped_Used_Car_data/Data/test.csv
Scrapped_Used_Car_data/Data/train.csv
Scrapped_Used_Car_data/Scrapping/used_car.csv
Scrapped_Used_Car_data/Scrapping/used_car_scrapping.py

Issue : #34 
- Developed an automation script using Selenium to navigate through target website and extract data.
- Each line of code is thoroughly explained through comments to clarify its purpose and functionality.
- Extracted raw data from the HTML content of the target webpage.
- Employed BeautifulSoup library to parse the HTML content and extract relevant data.
- Cleaned the extracted raw data to remove any irrelevant or erroneous information.
- Divided the cleaned data into train and test files .
- All code is written with detailed explanations accompanying each block or line.
- Comments provide insights into the logic behind the code, making it easier for others to understand and maintain.
- Requested peer review for the changes made in this pull request.

Scrapped Used Car details and Price data

---

backlog/ClusteringOfIMDBMovies.py

https://github.com/Recode-Hive/Scrape-ML/issues/64
1.We scrape IMDb data including movie titles, ratings, and summaries using BeautifulSoup
2.We use TF-IDF vectorization to convert the movie summaries into numerical feature vectors.
3.We apply K-means clustering to group the movies into clusters based on their summaries.
4.We use PCA for dimensionality reduction to visualize the clusters in a 2D space.
Co-authored-by: I Mercia Jeno [mercia.jeno@gmail.com](mailto:mercia.jeno@gmail.com)
Co-authored-by:  Bhakti Kalyankasture [kalyankasturebhakti@gmail.com](mailto:kalyankasturebhakti@gmail.com)

Clustering movie summaries added

---

.github/workflows/close-on-merge.yml

Fixes #103 
As the repo maintainers have to manually close an issue after merging a PR linked with that issue, I propose a workflow where the issue linked with a PR which be automatically closed when that PR is merged by the maintainer and efforts will be saved.

created close-on-merge.yml

---

main.py

#153 
[clustering movie data from imdb issue]
Description
1.We scrape IMDb data including movie titles, ratings, and summaries using BeautifulSoup
2.We use TF-IDF vectorization to convert the movie summaries into numerical feature vectors.
3.We apply K-means clustering to group the movies into clusters based on their summaries.
4.We use PCA for dimensionality reduction to visualize the clusters in a 2D space.
Co-authored-by: Mercia Jeno [mercia.jeno@gmail.com](mailto:mercia.jeno@gmail.com)
Co-authored-by: Bhakti Kalyankasture [kalyankasturebhakti@gmail.com](mailto:kalyankasturebhakti@gmail.com)

clustering movie data from imdb issue #153

---

Web_app/pages/1_Movie_Analysis.py
Web_app/utils.py

Fixes #217 
-**Fixed** the movie analysis page. 
-**Added** an **option selection feature** for the type of file encoding and appropriate error handling. 
-Also **fixed** analyze_reviews function in utils.py to have **parameter of column name** as per the uploaded user csv file.

Fixed Movie_Analysis Page

---

Web_app/pages/2_Movie_Recommendation.py

@sanjay-kv 
Addresses issue #231 
- Made dataframe start from 1
- Avoided self call
I have not made any changes to the model. I would love to work on it if allowed to do so

Fixed self call and made dataframe start from 1

---

Web_app/pages/FAQ.py

Added FAQ Page

---

.github/workflows/auto-label.yml

fixed #252 
**Overview** : This pull request addresses the issues with the "auto-label" GitHub workflow, ensuring that labels "gssoc-ext","hacktoberfest" and "hacktoberfest-accepted" are automatically applied to issues as intended.

Add: "auto-label" GitHub Workflow for Automated Labeling

---

Web_app/pages/GitContributors.py

fix: #253 
**ADD Github contributors page to the app, and Git link to the app** 

Add git contributors to the page

---

Web_app/movie_reviews.csv
Web_app/pages/API_Documentation.py
Web_app/pages/ReviewSubmission.py

fix: #254 
Review Page Description
The Review Page will serve as a dedicated space for users to view and analyze movie reviews collected from IMDb. It will display reviews in a structured format, allowing users to sort and filter by various criteria such as rating, date, and movie title. This page aims to enhance user experience by providing insights into viewer opinions and trends related to specific movies.
we will strore review in csv file, so that we donot require the backend to the app
API Documentation Page Description
The API Documentation Page will provide detailed information on the endpoints available for the IMDb Movie Review Scraper project. It will outline the request methods, parameters, response formats, and example usage for each endpoint. This documentation aims to assist …

ADD Review Submission Page and API Documentation Page

---

Web_app/Home_Page.py

fix: #233 
**video**
https://github.com/user-attachments/assets/00dc9082-9858-4a1c-892d-dcb1ded6a58b

Add content to sidebar

---

Web_app/Home_Page.py

Revamp home page

---

Web_app/pages/Trending_Movies.py

Add trending movies page

---

.github/workflows/auto-label-pr-merge.yml

**Purpose**: This PR adds automatic labeling for merged pull requests to streamline project management and enhance visibility.
**Labels Added:** Upon merging, the following labels will be automatically assigned:
- gssoc-ext
- hacktoberfest-accepted
**Benefit:** This automation will help in categorizing contributions efficiently and recognizing participants for their efforts.
Hey @sanjay-kv please review the PR

Add auto label on merged pr

---

Web_app/pages/ChangeLog.py

**This PR introduces a modernized changelog dashboard for Scrape ML, complete with:**
**Project Statistics:** Displaying total PRs merged, total contributors
**Merged PR Timeline:** A section showcasing the most recent 5 merged PRs with relevant details such as title, merge date, contributor, and profile image.
**Upcoming Features:** A dedicated section highlighting key upcoming features with progress bars.
Footer Update: Replaced the previous footer content with a brief description of Scrape ML and its purpose, along with team credits.

Add Scrape ML Changelog Dashboard and Merged PR Statistics

---

Web_app/pages/Favorite_Movie.py

Add fav movie page 

---

README.md

This pull request adds a bottom-to-top scroll-up button to improve user navigation by allowing them to quickly scroll back to the top of the page.
*A screenshot or video showing the scroll-up button functionality in action.*
@sanjay-kv Please review and merge it.

Added Back-to-top scroll up button
